name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Use Supabase API Key
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "Supabase API Key is $SUPABASE_KEY"
          # Now you can use $SUPABASE_KEY in your scripts or commands
